# -*- coding: utf-8 -*-
"""task07.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fUvOUSGnVqVck2NX8P9Zc4IFM1XxMho0
"""

#!pip install rdflib

import urllib.request

url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')

from validation import Report

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS


g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)


github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"
g.parse(github_storage + "/rdf/data06.ttl", format="ttl")

report = Report()

result = []

for s, p, o in g.triples((None, RDF.type, RDFS.Class)):
    superclase = False
    for s2, p2, o2 in g.triples((s, RDFS.subClassOf, None)):
        result.append((s, o2))
        superclase = True
    if not superclase:
        result.append((s, None))

for r in result:
    print(r)

report.validate_07_1a(result)

query = """
SELECT ?c ?sc
WHERE {
    ?c rdf:type rdfs:Class .
    OPTIONAL { ?c rdfs:subClassOf ?sc }
}
"""

for r in g.query(query):
    print(r.c, r.sc)

report.validate_07_1b(query, g)

from rdflib import RDF, RDFS, Namespace
ns = Namespace("http://oeg.fi.upm.es/def/people#")
individuals = []

def get_subclasses(cls):
    classes = [cls]
    for s, p, o in g.triples((None, RDFS.subClassOf, cls)):
        classes.extend(get_subclasses(s))
    return classes

person_classes = get_subclasses(ns.Person)

for cls in person_classes:
    for s, p, o in g.triples((None, RDF.type, cls)):
        if s not in individuals:
            individuals.append(s)

for i in individuals:
    print(i)

report.validate_07_02a(individuals)

query = """
PREFIX ns: <http://oeg.fi.upm.es/def/people#>
SELECT DISTINCT ?ind
WHERE {
    ?ind rdf:type ?type .
    ?type rdfs:subClassOf* ns:Person .
}
"""

for r in g.query(query):
    print(r.ind)

report.validate_07_02b(g, query)

query = """
SELECT ?name ?type
WHERE {
  ?person <http://oeg.fi.upm.es/def/people#knows> <http://oeg.fi.upm.es/def/people#Rocky> .
  ?person <http://www.w3.org/2000/01/rdf-schema#label> ?name .
  ?person a ?type .
}
"""

for r in g.query(query):
    print(r.name, r.type)

report.validate_07_03(g, query)

query = """
PREFIX ns: <http://oeg.fi.upm.es/def/people#>
SELECT ?name ?type
WHERE {
    ?person ns:knows ns:Rocky .
    ?person rdf:type ?type .
    ?person rdfs:label ?name .
}
"""
for r in g.query(query):
    print(r.name, r.type)

report.validate_07_03(g, query)

query = """
PREFIX ns: <http://oeg.fi.upm.es/def/people#>
SELECT DISTINCT ?name
WHERE {
    ?person rdfs:label ?name .
    {
        ?person ns:hasColleague ?colleague .
        ?colleague ns:ownsPet ?pet .
    }
    UNION
    {
        ?person ns:hasColleague ?col1 .
        ?col1 ns:hasColleague ?col2 .
        ?col2 ns:ownsPet ?pet .
    }
}
"""

for r in g.query(query):
    print(r.name)

report.validate_07_04(g,query)
report.save_report("_Task_07")
